--- # Connection
# ansible-playbook user.yaml 
# link: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
- name: Install packages
  hosts: all
  become: true
  become_method: sudo 
  user: ec2-user
  tasks: 
  - name: Add users
    when: ( ansible_facts['distribution'] == "Amazon" )
    ansible.builtin.user:
      name: "{{ item }}"
      generate_ssh_key: yes
      state: present
    with_items:
    - bob
    - ben
    - lisa
    - katty

  - name: Add users
    when: ( ansible_facts['distribution'] == "Amazon" )
      get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/"{{ item }}"
    with_items:
    - bob
    - ben
    - lisa
    - katty


  - name: Install mariabd derver
    when: ( ansible_facts['distribution'] == "Ubuntu" )
    ansible.builtin.group:
      name: 
      - mariabd server
      state: present